---
repos:
  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        entry: scripts/fmt.sh
        language: system
        pass_filenames: false
      - id: terraform-validate-examples
        name: terraform validate modules
        entry: scripts/validate.sh
        language: system
        pass_filenames: false
      - id: tflint
        name: tflint
        entry: scripts/lint.sh
        language: system
        pass_filenames: false
      - id: yamllint
        name: yamllint
        entry: scripts/yamllint.sh
        language: system
        pass_filenames: false
